<x-layouts.app title="Audit Logs Setup">
    <section class="flex flex-1 flex-col gap-6">
        <div>
            <h1 class="ui-page-header-title">Audit Logs Setup</h1>
            <p class="ui-page-header-copy">Configure audit policy and review activity records from their dedicated surfaces.</p>
        </div>

        <div class="grid gap-4 md:grid-cols-2">
            <a wire:navigate href="{{ route('platform.settings.audit-logs') }}" class="group rounded-lg border border-slate-800 bg-slate-900/70 p-6 transition hover:border-slate-600 hover:bg-slate-900">
                <p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-300">Settings</p>
                <h2 class="mt-2 text-xl font-semibold text-white">Audit Settings</h2>
                <p class="mt-2 text-sm text-slate-400">Set retention windows and login-event severity defaults.</p>
            </a>

            <a wire:navigate href="{{ route('platform.operations.audit-logs.index') }}" class="group rounded-lg border border-slate-800 bg-slate-900/70 p-6 transition hover:border-slate-600 hover:bg-slate-900">
                <p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-300">Viewer</p>
                <h2 class="mt-2 text-xl font-semibold text-white">Audit Log Viewer</h2>
                <p class="mt-2 text-sm text-slate-400">Search and review audit records generated by platform operations.</p>
            </a>
        </div>
    </section>
</x-layouts.app>
