<x-layouts.app title="Audit Logs Setup">
    <section class="flex flex-1 flex-col gap-6">
        <div class="rounded-3xl border border-slate-800 bg-slate-900/70 p-8 shadow-2xl shadow-black/30">
            <p class="text-sm font-medium uppercase tracking-[0.3em] text-sky-300">Setup</p>
            <h1 class="mt-3 text-3xl font-semibold text-white">Audit Logs Setup</h1>
            <p class="mt-2 text-slate-400">Configure audit policy and review activity records from their dedicated surfaces.</p>
        </div>

        <div class="grid gap-4 md:grid-cols-2">
            <a href="{{ route('platform.settings.audit-logs') }}" class="group rounded-3xl border border-slate-800 bg-slate-900/70 p-6 transition hover:border-sky-500/40 hover:bg-slate-900">
                <p class="text-xs font-semibold uppercase tracking-[0.2em] text-sky-300">Settings</p>
                <h2 class="mt-2 text-xl font-semibold text-white">Audit Settings</h2>
                <p class="mt-2 text-sm text-slate-400">Set retention windows and login-event severity defaults.</p>
            </a>

            <a href="{{ route('platform.audit-logs.index') }}" class="group rounded-3xl border border-slate-800 bg-slate-900/70 p-6 transition hover:border-sky-500/40 hover:bg-slate-900">
                <p class="text-xs font-semibold uppercase tracking-[0.2em] text-sky-300">Viewer</p>
                <h2 class="mt-2 text-xl font-semibold text-white">Audit Log Viewer</h2>
                <p class="mt-2 text-sm text-slate-400">Search and review audit records generated by platform operations.</p>
            </a>
        </div>
    </section>
</x-layouts.app>
