{{-- ==========================================================================
    File: Modules/Auth/resources/views/mfa-challenge.blade.php
    Purpose: MFA authenticator challenge step.

    Flow:
    - Step 1: identifier and password have already been verified.
    - Step 2: collect the authenticator app code.
    - Alternate path: collect a saved recovery code from the modal.

    Notes:
    - Uses x-patterns.auth.challenge-form for the shared auth shell, panel,
      header, alerts, form wrapper, account context, and help footer.
    - Keeps MFA method, authenticator code field, recovery-code helper, modal,
      and action controls explicit in this view.
    ========================================================================== --}}

<x-layouts.app title="Authentication" :grid="false">
    <x-patterns.auth.challenge-form
        title="Authentication"
        description="Enter the 6-digit code generated by your authenticator app."
        :action="route('mfa.challenge.verify')"
        :context="$user->email"
        context-label="Signing in as"
        help-text="Still having trouble?"
        actions-width="full"
        actions-alignment="stretch"
        :actions-auto-stack="false"
        actions-loading-text="Verifying code..."
    >
        <input type="hidden" name="mfa_method" value="totp" />

        {{-- --------------------------------------------------------------
            Form fields and recovery helper
            ----------------------------------------------------------- --}}
        <div class="mb-6 space-y-5">
            {{-- ----------------------------------------------------------
                Authenticator code
                ------------------------------------------------------- --}}
            <x-ui.text-input
                id="code"
                name="code"
                label="Authenticator code"
                class="ui-text-input--fluid"
                required
                inputmode="numeric"
                autocomplete="one-time-code"
                autofocus
                :invalid="$errors->has('code') && old('mfa_method') !== 'recovery_code'"
                :invalid-text="$errors->first('code')"
            />

            {{-- ----------------------------------------------------------
                Recovery-code option
                ------------------------------------------------------- --}}
            <div class="px-4">
                <p class="ui-platform-text-muted text-sm leading-6">Can't access your app?

                <x-ui.link href="#mfa-recovery-code-modal" text="Use a recovery code" variant="inline" />

                instead.</p>
            </div>
        </div>

        {{-- --------------------------------------------------------------
            Form actions

            challenge-form wraps these buttons with common-actions.form-actions.
            ----------------------------------------------------------- --}}
        <x-slot:actions>
            <x-ui.button type="button" kind="ghost" size="xl" disabled>
                Alternate verification
            </x-ui.button>

            <x-ui.button
                type="submit"
                kind="primary"
                size="xl"
                icon="arrow--right"
            >
                Verify code
            </x-ui.button>
        </x-slot:actions>
    </x-patterns.auth.challenge-form>

    {{-- ------------------------------------------------------------------
        Recovery code modal
        ------------------------------------------------------------------ --}}
    <x-ui.modal
        id="mfa-recovery-code-modal"
        title="Use a recovery code"
        description="Enter one saved recovery code. Recovery codes are single use."
        size="sm"
        :open="$errors->has('code') && old('mfa_method') === 'recovery_code'"
    >
        <form
            id="mfa-recovery-code-form"
            method="POST"
            action="{{ route('mfa.challenge.verify') }}"
            class="ui-form--fluid space-y-5"
            novalidate
        >
            @csrf

            <input type="hidden" name="mfa_method" value="recovery_code" />

            <x-ui.text-input
                id="recovery_code"
                name="code"
                label="Recovery code"
                class="ui-text-input--fluid"
                required
                autocomplete="one-time-code"
                :invalid="$errors->has('code') && old('mfa_method') === 'recovery_code'"
                :invalid-text="$errors->first('code')"
            />
        </form>

        <x-slot:actions>
            <x-patterns.forms.actions
                label="Recovery code actions"
                alignment="stretch"
                fluid
                width="full"
                :auto-stack="false"
                loading-text="Verifying recovery code..."
            >
                <x-ui.button
                    type="button"
                    kind="ghost"
                    size="xl"
                    data-ui-modal-close
                >
                    Cancel
                </x-ui.button>

                <x-ui.button
                    type="submit"
                    kind="primary"
                    size="xl"
                    icon="arrow--right"
                    form="mfa-recovery-code-form"
                >
                    Verify recovery code
                </x-ui.button>
            </x-patterns.forms.actions>
        </x-slot:actions>
    </x-ui.modal>
</x-layouts.app>
