<?php

declare(strict_types=1);

return [
    'resources/css/components/accordion.css:105 margin: 0',
    'resources/css/components/accordion.css:269 margin: 2px 0 0 var(--ui-accordion-padding-inline)',
    'resources/css/components/accordion.css:276 margin-inline-end: var(--ui-spacing-05)',
    'resources/css/components/accordion.css:283 margin-inline-start: calc( var(--ui-accordion-padding-inline) + var(--ui-spacing-05) )',
    'resources/css/components/accordion.css:31 margin: 0',
    'resources/css/components/accordion.css:409 margin-inline-start: var(--ui-spacing-05)',
    'resources/css/components/accordion.css:523 margin-inline-start: var(--ui-spacing-05)',
    'resources/css/components/accordion.css:539 margin-block-end: 0',
    'resources/css/components/accordion.css:544 margin-inline-start: var(--ui-spacing-05)',
    'resources/css/components/accordion.css:562 margin-inline-end: 0',
    'resources/css/components/actionable-notification.css:230 margin-block-start: 0.875rem',
    'resources/css/components/actionable-notification.css:231 margin-inline-end: var(--ui-spacing-05)',
    'resources/css/components/actionable-notification.css:238 margin-block-start: var(--ui-spacing-05)',
    'resources/css/components/actionable-notification.css:239 margin-inline-end: var(--ui-spacing-05)',
    'resources/css/components/actionable-notification.css:26 margin: 0',
    'resources/css/components/actionable-notification.css:279 margin-inline: 0.8125rem var(--ui-spacing-09)',
    'resources/css/components/actionable-notification.css:291 margin: 0 0.8125rem',
    'resources/css/components/actionable-notification.css:340 margin-inline-end: var(--ui-spacing-02)',
    'resources/css/components/actionable-notification.css:352 margin-inline-end: 0',
    'resources/css/components/actionable-notification.css:357 margin-block-start: 0',
    'resources/css/components/actionable-notification.css:387 margin-block-end: var(--ui-spacing-03)',
    'resources/css/components/actionable-notification.css:388 margin-inline-start: var(--ui-spacing-08)',
    'resources/css/components/actionable-notification.css:398 margin: var(--ui-spacing-03) 0',
    'resources/css/components/actionable-notification.css:484 margin-block-end: var(--ui-spacing-05)',
    'resources/css/components/actionable-notification.css:485 margin-inline-start: calc(var(--ui-spacing-07) + 1.25rem - 0.125rem)',
    'resources/css/components/actionable-notification.css:615 margin-inline-end: var(--ui-spacing-03)',
    'resources/css/components/badge-indicator.css:26 margin-block-start: var(--ui-spacing-03)',
    'resources/css/components/badge-indicator.css:27 margin-inline-end: var(--ui-spacing-03)',
    'resources/css/components/badge-indicator.css:46 margin-block-start: var(--ui-spacing-02)',
    'resources/css/components/badge-indicator.css:47 margin-inline-end: var(--ui-spacing-02)',
    'resources/css/components/breadcrumb.css:20 margin: 0',
    'resources/css/components/breadcrumb.css:204 margin: 0 auto',
    'resources/css/components/breadcrumb.css:58 margin-inline-end: var(--ui-spacing-03)',
    'resources/css/components/breadcrumb.css:63 margin-inline-end: var(--ui-spacing-02)',
    'resources/css/components/breadcrumb.css:73 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/breadcrumb.css:80 margin-inline-start: var(--ui-spacing-02)',
    'resources/css/components/breadcrumb.css:90 margin-inline-end: 0',
    'resources/css/components/button.css:199 margin-block-start: 0',
    'resources/css/components/button.css:200 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/button.css:296 margin-block-start: 0',
    'resources/css/components/button.css:297 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/button.css:377 margin-block-start: 0',
    'resources/css/components/button.css:406 margin-block-start: 1px',
    'resources/css/components/button.css:42 margin: 0',
    'resources/css/components/button.css:467 margin: 0',
    'resources/css/components/button.css:478 margin: 0',
    'resources/css/components/button.css:516 margin-block-start: var(--ui-spacing-02)',
    'resources/css/components/button.css:517 margin-inline-end: var(--ui-spacing-02)',
    'resources/css/components/checkbox.css:112 margin-block: 0.0625rem 0.125rem',
    'resources/css/components/checkbox.css:113 margin-inline: 0.1875rem 0',
    'resources/css/components/checkbox.css:126 margin-block-start: -0.1875rem',
    'resources/css/components/checkbox.css:22 margin: 0',
    'resources/css/components/checkbox.css:267 margin-block-start: var(--ui-spacing-02)',
    'resources/css/components/checkbox.css:273 margin: 0.0625rem 0.0625rem 0 0.1875rem',
    'resources/css/components/checkbox.css:31 margin-block-end: 0.375rem',
    'resources/css/components/checkbox.css:35 margin-block-start: 0',
    'resources/css/components/checkbox.css:39 margin-block-start: calc(var(--ui-spacing-01) * -1)',
    'resources/css/components/checkbox.css:407 margin-block-start: 0',
    'resources/css/components/checkbox.css:408 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/checkbox.css:43 margin-block-end: 0.1875rem',
    'resources/css/components/checkbox.css:532 margin-block: 0.0625rem 0',
    'resources/css/components/checkbox.css:533 margin-inline: 0.375rem 0',
    'resources/css/components/checkbox.css:55 margin: -1px',
    'resources/css/components/checkbox.css:565 margin-block-start: 0',
    'resources/css/components/checkbox.css:566 margin-inline-start: -0.0625rem',
    'resources/css/components/checkbox.css:602 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/checkbox.css:662 margin-inline-start: 0',
    'resources/css/components/checkbox.css:682 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/checkbox.css:699 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/checkbox.css:754 margin-block-start: -0.0625rem',
    'resources/css/components/checkbox.css:78 margin: 0',
    'resources/css/components/checkbox.css:809 margin-inline-start: 0',
    'resources/css/components/checkbox.css:827 margin-block-end: 0',
    'resources/css/components/checkbox.css:832 margin-inline-end: var(--ui-spacing-05)',
    'resources/css/components/checkbox.css:844 margin-block-start: 0',
    'resources/css/components/code-snippet.css:107 margin: 0',
    'resources/css/components/code-snippet.css:183 margin: auto',
    'resources/css/components/code-snippet.css:38 margin: 0',
    'resources/css/components/code-snippet.css:464 margin: 0',
    'resources/css/components/code-snippet.css:558 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/code-snippet.css:615 margin-block-start: 0.5rem',
    'resources/css/components/code-snippet.css:62 margin: 0',
    'resources/css/components/code-snippet.css:629 margin: 0',
    'resources/css/components/contained-list.css:119 margin-block-start: var(--ui-spacing-05)',
    'resources/css/components/contained-list.css:178 margin-block-start: -1px',
    'resources/css/components/contained-list.css:223 margin: 0',
    'resources/css/components/contained-list.css:33 margin: 0',
    'resources/css/components/contained-list.css:344 margin: 0',
    'resources/css/components/contained-list.css:363 margin: 0',
    'resources/css/components/contained-list.css:399 margin: 0',
    'resources/css/components/contained-list.css:439 margin-inline-start: auto',
    'resources/css/components/content-switcher.css:334 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/content-switcher.css:385 margin-block-start: var(--ui-spacing-05)',
    'resources/css/components/content-switcher.css:398 margin-block-end: var(--ui-spacing-02)',
    'resources/css/components/content-switcher.css:66 margin: 0',
    'resources/css/components/content-switcher.css:87 margin: 0',
    'resources/css/components/copy-button.css:113 margin: auto',
    'resources/css/components/copy-button.css:25 margin: 0',
    'resources/css/components/data-table-expandable.css:156 margin: 0',
    'resources/css/components/data-table-skeleton.css:86 margin-block-start: var(--ui-spacing-03)',
    'resources/css/components/data-table-sort.css:114 margin-inline: var(--ui-spacing-03) var(--ui-spacing-05)',
    'resources/css/components/data-table-sort.css:42 margin: 0',
    'resources/css/components/data-table-toolbar.css:193 margin: 0',
    'resources/css/components/data-table-toolbar.css:244 margin: 0',
    'resources/css/components/data-table-toolbar.css:349 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/data-table.css:392 margin-inline-end: var(--ui-spacing-03)',
    'resources/css/components/data-table.css:497 margin-block-start: 0.125rem',
    'resources/css/components/data-table.css:531 margin-inline-end: -0.125rem',
    'resources/css/components/date-picker.css:134 margin-inline-end: 1px',
    'resources/css/components/date-picker.css:156 margin: 0',
    'resources/css/components/dialog.css:228 margin-block-end: var(--ui-spacing-03)',
    'resources/css/components/dialog.css:24 margin: auto',
    'resources/css/components/dialog.css:244 margin: 0',
    'resources/css/components/dialog.css:245 margin-block-end: var(--ui-spacing-02)',
    'resources/css/components/dialog.css:259 margin: 0',
    'resources/css/components/dialog.css:318 margin-block-end: var(--ui-spacing-06)',
    'resources/css/components/dialog.css:346 margin: 0',
    'resources/css/components/dropdown.css:328 margin: 0',
    'resources/css/components/dropdown.css:422 margin: 0 var(--ui-spacing-05)',
    'resources/css/components/dropdown.css:454 margin: 0',
    'resources/css/components/dropdown.css:464 margin: 0 var(--ui-spacing-05)',
    'resources/css/components/dropdown.css:473 margin: 0',
    'resources/css/components/dropdown.css:51 margin: 0',
    'resources/css/components/dropdown.css:71 margin: 0',
    'resources/css/components/file-uploader.css:161 margin-block-start: var(--ui-spacing-06)',
    'resources/css/components/file-uploader.css:166 margin-block-start: var(--ui-spacing-05)',
    'resources/css/components/file-uploader.css:171 margin-block-start: var(--ui-spacing-03)',
    'resources/css/components/file-uploader.css:187 margin-block-end: var(--ui-spacing-03)',
    'resources/css/components/file-uploader.css:194 margin-block-end: 0',
    'resources/css/components/file-uploader.css:202 margin: 0',
    'resources/css/components/file-uploader.css:209 margin-inline-end: 0',
    'resources/css/components/file-uploader.css:236 margin-inline-start: var(--ui-spacing-05)',
    'resources/css/components/file-uploader.css:248 margin-block-start: 1px',
    'resources/css/components/file-uploader.css:25 margin-inline-end: var(--ui-spacing-03)',
    'resources/css/components/file-uploader.css:314 margin-block-end: var(--ui-spacing-03)',
    'resources/css/components/file-uploader.css:35 margin: 0',
    'resources/css/components/file-uploader.css:36 margin-block-end: var(--ui-spacing-03)',
    'resources/css/components/file-uploader.css:514 margin-inline-end: calc(-1 * var(--ui-spacing-03))',
    'resources/css/components/file-uploader.css:52 margin: 0',
    'resources/css/components/file-uploader.css:528 margin: 0',
    'resources/css/components/file-uploader.css:53 margin-block-end: var(--ui-spacing-05)',
    'resources/css/components/file-uploader.css:75 margin: -1px',
    'resources/css/components/file-uploader.css:90 margin: 0',
    'resources/css/components/fluid-date-picker.css:50 margin: 0',
    'resources/css/components/fluid-list-box.css:272 margin-block-start: 0',
    'resources/css/components/fluid-list-box.css:398 margin: 0 var(--ui-spacing-05)',
    'resources/css/components/fluid-list-box.css:50 margin: 0',
    'resources/css/components/fluid-multi-select.css:46 margin-block-start: 1.25rem',
    'resources/css/components/fluid-number-input.css:39 margin: 0',
    'resources/css/components/fluid-number-input.css:432 margin: 0 var(--ui-spacing-05)',
    'resources/css/components/fluid-number-input.css:439 margin: 0',
    'resources/css/components/fluid-search.css:130 margin-block-end: 0.125rem',
    'resources/css/components/fluid-search.css:38 margin: 0',
    'resources/css/components/fluid-select.css:136 margin: 0 var(--ui-spacing-05)',
    'resources/css/components/fluid-select.css:217 margin: 0',
    'resources/css/components/fluid-select.css:44 margin: 0',
    'resources/css/components/fluid-text-area.css:121 margin-block-start: 2rem',
    'resources/css/components/fluid-text-area.css:170 margin-block-start: 1.875rem',
    'resources/css/components/fluid-text-area.css:207 margin: 0 1rem',
    'resources/css/components/fluid-text-area.css:265 margin: 0',
    'resources/css/components/fluid-text-area.css:482 margin-block-end: var(--ui-spacing-04)',
    'resources/css/components/fluid-text-area.css:57 margin: 0',
    'resources/css/components/fluid-text-area.css:87 margin-inline-start: calc(var(--ui-spacing-02) * -1)',
    'resources/css/components/fluid-text-input.css:168 margin: 0',
    'resources/css/components/fluid-text-input.css:201 margin: 0 1rem',
    'resources/css/components/fluid-text-input.css:44 margin: 0',
    'resources/css/components/form.css:107 margin: 0',
    'resources/css/components/form.css:352 margin: 0',
    'resources/css/components/form.css:353 margin-block-end: 0',
    'resources/css/components/form.css:37 margin: 0',
    'resources/css/components/form.css:426 margin: 0',
    'resources/css/components/form.css:449 margin: var(--ui-spacing-02) 0 0',
    'resources/css/components/form.css:470 margin-block-start: 0',
    'resources/css/components/form.css:477 margin-block-start: var(--ui-spacing-02)',
    'resources/css/components/form.css:67 margin: 0',
    'resources/css/components/form.css:68 margin-block-end: var(--ui-spacing-03)',
    'resources/css/components/form.css:88 margin-block-end: 0',
    'resources/css/components/icon-button.css:39 margin: 0',
    'resources/css/components/icon-indicator.css:29 margin-inline-end: var(--ui-spacing-03)',
    'resources/css/components/inline-loading.css:40 margin-inline-end: var(--ui-spacing-03)',
    'resources/css/components/inline-notification.css:203 margin-block-start: 0.875rem',
    'resources/css/components/inline-notification.css:204 margin-inline-end: var(--ui-spacing-05)',
    'resources/css/components/inline-notification.css:232 margin-inline: 0.8125rem var(--ui-spacing-09)',
    'resources/css/components/inline-notification.css:238 margin: 0 0.8125rem',
    'resources/css/components/inline-notification.css:251 margin-inline-end: var(--ui-spacing-02)',
    'resources/css/components/inline-notification.css:26 margin: 0',
    'resources/css/components/inline-notification.css:280 margin-block-end: var(--ui-spacing-03)',
    'resources/css/components/inline-notification.css:281 margin-inline-start: var(--ui-spacing-08)',
    'resources/css/components/inline-notification.css:291 margin: var(--ui-spacing-03) 0',
    'resources/css/components/inline-notification.css:371 margin-inline-end: var(--ui-spacing-03)',
    'resources/css/components/link.css:206 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/link.css:30 margin: 0',
    'resources/css/components/list-box.css:30 margin: 0',
    'resources/css/components/list-box.css:40 margin: 0',
    'resources/css/components/list-box.css:572 margin-inline-end: 0.625rem',
    'resources/css/components/list-box.css:587 margin-inline-start: 0.25rem',
    'resources/css/components/list-box.css:620 margin-inline-start: 2.0625rem',
    'resources/css/components/list-box.css:637 margin-inline-end: 2.0625rem',
    'resources/css/components/list-box.css:655 margin: 0',
    'resources/css/components/list-box.css:753 margin: 0 var(--ui-spacing-05)',
    'resources/css/components/list-box.css:779 margin: 0',
    'resources/css/components/list-box.css:793 margin: 0 var(--ui-spacing-03)',
    'resources/css/components/list-box.css:798 margin: 0',
    'resources/css/components/list.css:27 margin: 0',
    'resources/css/components/list.css:41 margin-inline-start: var(--ui-spacing-05)',
    'resources/css/components/list.css:76 margin-inline-start: 2rem',
    'resources/css/components/menu.css:168 margin: 0',
    'resources/css/components/menu.css:24 margin: 0',
    'resources/css/components/menu.css:316 margin-block: var(--ui-spacing-02)',
    'resources/css/components/modal.css:219 margin-inline: calc(var(--ui-spacing-03) * -1)',
    'resources/css/components/modal.css:246 margin-block-end: var(--ui-spacing-03)',
    'resources/css/components/modal.css:254 margin: 0',
    'resources/css/components/modal.css:255 margin-block-end: var(--ui-spacing-02)',
    'resources/css/components/modal.css:269 margin: 0',
    'resources/css/components/modal.css:435 margin-block-end: var(--ui-spacing-06)',
    'resources/css/components/modal.css:448 margin-block-start: auto',
    'resources/css/components/modal.css:456 margin: 0',
    'resources/css/components/modal.css:535 margin: 0',
    'resources/css/components/multi-select.css:124 margin: 0',
    'resources/css/components/multi-select.css:190 margin-block: 0',
    'resources/css/components/multi-select.css:224 margin: 0',
    'resources/css/components/multi-select.css:347 margin: 0 0 0 var(--ui-spacing-05)',
    'resources/css/components/multi-select.css:71 margin: 0 var(--ui-spacing-03) 0 var(--ui-spacing-05)',
    'resources/css/components/number-input.css:252 margin: 0',
    'resources/css/components/number-input.css:26 margin: 0',
    'resources/css/components/number-input.css:286 margin: 0',
    'resources/css/components/number-input.css:68 margin: 0',
    'resources/css/components/number-input.css:842 margin-block-start: 0',
    'resources/css/components/overflow-menu.css:172 margin: 0',
    'resources/css/components/overflow-menu.css:31 margin: 0',
    'resources/css/components/overflow-menu.css:314 margin: 0',
    'resources/css/components/overflow-menu.css:382 margin: 0',
    'resources/css/components/overflow-menu.css:64 margin-block-start: 0',
    'resources/css/components/page-header.css:104 margin-block-end: 1rem',
    'resources/css/components/page-header.css:158 margin-inline-end: var(--ui-spacing-05)',
    'resources/css/components/page-header.css:163 margin-block-end: var(--ui-spacing-03)',
    'resources/css/components/page-header.css:174 margin-block-start: var(--ui-spacing-03)',
    'resources/css/components/page-header.css:226 margin-inline-start: calc(var(--ui-spacing-05) * -1)',
    'resources/css/components/page-header.css:274 margin-block-start: 0',
    'resources/css/components/page-header.css:59 margin-inline-end: var(--ui-spacing-03)',
    'resources/css/components/page-header.css:73 margin-inline-end: var(--ui-spacing-04)',
    'resources/css/components/page-header.css:83 margin-inline-end: 0',
    'resources/css/components/pagination-nav.css:284 margin: -1px',
    'resources/css/components/pagination-nav.css:37 margin: 0',
    'resources/css/components/pagination-nav.css:57 margin: 0',
    'resources/css/components/pagination-nav.css:86 margin: 0',
    'resources/css/components/pagination.css:158 margin-inline-end: 1px',
    'resources/css/components/pagination.css:163 margin-inline: 1px var(--ui-spacing-05)',
    'resources/css/components/pagination.css:168 margin-inline: var(--ui-spacing-05) 1px',
    'resources/css/components/pagination.css:175 margin-inline-end: var(--ui-spacing-05)',
    'resources/css/components/pagination.css:180 margin: 0',
    'resources/css/components/pagination.css:185 margin-inline-start: var(--ui-spacing-05)',
    'resources/css/components/pagination.css:284 margin: 0',
    'resources/css/components/pagination.css:323 margin-block-start: 0',
    'resources/css/components/pagination.css:413 margin-block-end: 0',
    'resources/css/components/pagination.css:414 margin-inline-end: var(--ui-spacing-05)',
    'resources/css/components/pagination.css:51 margin: 0',
    'resources/css/components/popover.css:133 margin: 0',
    'resources/css/components/progress-bar.css:152 margin-block-start: var(--ui-spacing-03)',
    'resources/css/components/progress-bar.css:163 margin-inline-start: var(--ui-progress-bar-padding-inline)',
    'resources/css/components/progress-bar.css:227 margin-block-end: 0',
    'resources/css/components/progress-bar.css:228 margin-inline-end: var(--ui-progress-bar-padding-inline)',
    'resources/css/components/progress-bar.css:245 margin: -1px',
    'resources/css/components/progress-bar.css:264 margin: -1px',
    'resources/css/components/progress-bar.css:283 margin-inline-end: 0',
    'resources/css/components/progress-bar.css:36 margin-block-end: var(--ui-spacing-03)',
    'resources/css/components/progress-indicator.css:105 margin: calc(-1 * var(--ui-spacing-01))',
    'resources/css/components/progress-indicator.css:113 margin: var(--ui-spacing-03) 0 0',
    'resources/css/components/progress-indicator.css:142 margin-inline-end: 0.75rem',
    'resources/css/components/progress-indicator.css:149 margin-block-start: 1.75rem',
    'resources/css/components/progress-indicator.css:150 margin-inline-start: var(--ui-spacing-06)',
    'resources/css/components/progress-indicator.css:166 margin: 0',
    'resources/css/components/progress-indicator.css:22 margin: 0',
    'resources/css/components/progress-indicator.css:231 margin-inline-start: 0.625rem',
    'resources/css/components/progress-indicator.css:236 margin: 0',
    'resources/css/components/progress-indicator.css:246 margin-block-start: 2.5rem',
    'resources/css/components/progress-indicator.css:247 margin-inline-start: 1.375rem',
    'resources/css/components/progress-indicator.css:351 margin-block-start: 0.625rem',
    'resources/css/components/progress-indicator.css:374 margin-block-start: 0.0625rem',
    'resources/css/components/progress-indicator.css:402 margin: 0.0625rem var(--ui-spacing-03) 0',
    'resources/css/components/progress-indicator.css:410 margin: 0',
    'resources/css/components/progress-indicator.css:417 margin-block-start: 0.5rem',
    'resources/css/components/progress-indicator.css:424 margin: 0 0 auto',
    'resources/css/components/progress-indicator.css:82 margin-block-start: 0.625rem',
    'resources/css/components/progress-indicator.css:83 margin-inline-end: var(--ui-spacing-03)',
    'resources/css/components/radio-button.css:111 margin-block: 0.0625rem 0.125rem',
    'resources/css/components/radio-button.css:112 margin-inline: 0.125rem 0.625rem',
    'resources/css/components/radio-button.css:123 margin-block: 0',
    'resources/css/components/radio-button.css:25 margin: 0',
    'resources/css/components/radio-button.css:300 margin-block-start: 0.375rem',
    'resources/css/components/radio-button.css:305 margin-inline: 0.1875rem 0.0625rem',
    'resources/css/components/radio-button.css:359 margin-block-start: 0',
    'resources/css/components/radio-button.css:360 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/radio-button.css:37 margin-block-start: 0',
    'resources/css/components/radio-button.css:380 margin-block-start: 0.375rem',
    'resources/css/components/radio-button.css:432 margin: 0',
    'resources/css/components/radio-button.css:436 margin-inline-end: var(--ui-spacing-05)',
    'resources/css/components/radio-button.css:441 margin-block-end: 0.375rem',
    'resources/css/components/radio-button.css:442 margin-inline-end: 0',
    'resources/css/components/radio-button.css:506 margin-inline: var(--ui-spacing-03) 0',
    'resources/css/components/radio-button.css:55 margin-inline-end: 0',
    'resources/css/components/radio-button.css:63 margin-block-end: var(--ui-spacing-03)',
    'resources/css/components/radio-button.css:73 margin: -1px',
    'resources/css/components/radio-button.css:91 margin-inline-end: var(--ui-spacing-05)',
    'resources/css/components/search.css:160 margin: 0',
    'resources/css/components/search.css:199 margin: 0',
    'resources/css/components/search.css:275 margin-inline-start: var(--ui-spacing-01)',
    'resources/css/components/search.css:443 margin: 0',
    'resources/css/components/search.css:499 margin: 0',
    'resources/css/components/search.css:51 margin: -1px',
    'resources/css/components/search.css:664 margin: 0',
    'resources/css/components/search.css:680 margin: 0',
    'resources/css/components/search.css:69 margin: 0',
    'resources/css/components/search.css:716 margin: 0',
    'resources/css/components/search.css:732 margin: 0',
    'resources/css/components/select.css:291 margin-block-end: 0',
    'resources/css/components/select.css:292 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/select.css:297 margin: 0 var(--ui-spacing-03) 0 0',
    'resources/css/components/select.css:46 margin: 0',
    'resources/css/components/select.css:73 margin: 0',
    'resources/css/components/shape-indicator.css:32 margin-inline-end: var(--ui-spacing-03)',
    'resources/css/components/slider.css:33 margin-inline: 0.25rem',
    'resources/css/components/slug.css:902 margin: 0',
    'resources/css/components/structured-list.css:109 margin: 0',
    'resources/css/components/structured-list.css:27 margin: 0',
    'resources/css/components/structured-list.css:287 margin: -1px',
    'resources/css/components/structured-list.css:304 margin-block-start: var(--ui-spacing-01)',
    'resources/css/components/structured-list.css:87 margin: 0',
    'resources/css/components/tabs.css:101 margin: 0',
    'resources/css/components/tabs.css:132 margin: 0',
    'resources/css/components/tabs.css:326 margin: 0',
    'resources/css/components/tabs.css:342 margin-inline-start: 1px',
    'resources/css/components/tabs.css:349 margin-inline-start: 0',
    'resources/css/components/tabs.css:377 margin: 0',
    'resources/css/components/tabs.css:477 margin-inline-start: calc(-1 * var(--ui-spacing-06) + 1px)',
    'resources/css/components/tabs.css:488 margin: -1px',
    'resources/css/components/tabs.css:49 margin: 0',
    'resources/css/components/tabs.css:507 margin: 0',
    'resources/css/components/tabs.css:578 margin-block-start: -2px',
    'resources/css/components/tabs.css:611 margin-inline-end: 1px',
    'resources/css/components/tabs.css:638 margin-block-start: var(--ui-spacing-02)',
    'resources/css/components/tabs.css:639 margin-inline-end: var(--ui-spacing-02)',
    'resources/css/components/tabs.css:823 margin-inline-start: 0',
    'resources/css/components/tabs.css:981 margin-inline-start: auto',
    'resources/css/components/tag.css:138 margin-inline-end: var(--ui-spacing-02)',
    'resources/css/components/tag.css:232 margin-inline-end: var(--ui-spacing-04)',
    'resources/css/components/tag.css:237 margin-inline-end: var(--ui-spacing-03)',
    'resources/css/components/text-area.css:167 margin: -1px',
    'resources/css/components/text-area.css:72 margin: 0',
    'resources/css/components/text-input.css:236 margin: 0',
    'resources/css/components/text-input.css:420 margin: -1px',
    'resources/css/components/text-input.css:513 margin: 0',
    'resources/css/components/text-input.css:558 margin: 0 var(--ui-spacing-05)',
    'resources/css/components/text-input.css:665 margin: 0',
    'resources/css/components/text-input.css:680 margin-inline-end: var(--ui-spacing-03)',
    'resources/css/components/text-input.css:685 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/text-input.css:690 margin-block-start: 0.125rem',
    'resources/css/components/text-input.css:699 margin: 0',
    'resources/css/components/text-input.css:96 margin: 0',
    'resources/css/components/tile.css:24 margin: 0',
    'resources/css/components/tile.css:428 margin: 0',
    'resources/css/components/tile.css:465 margin: -1px',
    'resources/css/components/tile.css:588 margin-block-start: var(--ui-spacing-03)',
    'resources/css/components/tile.css:593 margin-block-start: var(--ui-spacing-03)',
    'resources/css/components/tile.css:90 margin: 0',
    'resources/css/components/toast-notification.css:182 margin-block-start: var(--ui-spacing-05)',
    'resources/css/components/toast-notification.css:183 margin-inline-end: var(--ui-spacing-05)',
    'resources/css/components/toast-notification.css:205 margin-block-end: var(--ui-spacing-05)',
    'resources/css/components/toast-notification.css:206 margin-inline-end: var(--ui-spacing-05)',
    'resources/css/components/toast-notification.css:21 margin: 0',
    'resources/css/components/toast-notification.css:211 margin-block-start: var(--ui-spacing-05)',
    'resources/css/components/toast-notification.css:221 margin-block: 0 var(--ui-spacing-05)',
    'resources/css/components/toast-notification.css:254 margin-inline-start: auto',
    'resources/css/components/toggle.css:34 margin-block-end: var(--ui-spacing-05)',
    'resources/css/components/toggle.css:451 margin-inline-start: 0.5rem',
    'resources/css/components/toggle.css:48 margin-block-end: var(--ui-spacing-03)',
    'resources/css/components/toggle.css:59 margin: -1px',
    'resources/css/components/toggletip.css:109 margin: 0',
    'resources/css/components/toggletip.css:116 margin: 0',
    'resources/css/components/toggletip.css:21 margin-inline-end: var(--ui-spacing-03)',
    'resources/css/components/toggletip.css:236 margin: 0',
    'resources/css/components/toggletip.css:63 margin: 0',
    'resources/css/components/tooltip.css:304 margin-inline-start: calc(-1 * var(--ui-tooltip-caret-size) / 2)',
    'resources/css/components/tooltip.css:311 margin-inline-start: calc(-1 * var(--ui-tooltip-caret-size) / 2)',
    'resources/css/components/tooltip.css:318 margin-block-start: calc(-1 * var(--ui-tooltip-caret-size) / 2)',
    'resources/css/components/tooltip.css:325 margin-block-start: calc(-1 * var(--ui-tooltip-caret-size) / 2)',
    'resources/css/components/tooltip.css:365 margin-inline-start: 0',
    'resources/css/components/tooltip.css:373 margin-inline-start: 0',
    'resources/css/components/tooltip.css:69 margin: 0',
    'resources/css/components/tree-view.css:104 margin-inline-start: var(--ui-spacing-03)',
    'resources/css/components/tree-view.css:235 margin-inline: calc(-1 * var(--ui-spacing-02)) var(--ui-spacing-02)',
    'resources/css/components/tree-view.css:25 margin: 0',
    'resources/css/components/tree-view.css:257 margin-inline-end: 0',
    'resources/css/components/tree-view.css:303 margin-inline: var(--ui-spacing-03)',
    'resources/css/components/tree-view.css:322 margin-inline-start: var(--ui-spacing-02)',
    'resources/css/components/tree-view.css:509 margin-block-start: 0',
    'resources/css/components/tree-view.css:78 margin: 0',
    'resources/css/components/tree-view.css:85 margin-block-start: var(--ui-spacing-02)',
    'resources/css/components/tree-view.css:86 margin-inline-start: var(--ui-spacing-06)',
    'resources/css/components/ui-shell/content.css:102 margin: 0',
    'resources/css/components/ui-shell/content.css:112 margin: 0.75rem 0 0',
    'resources/css/components/ui-shell/content.css:119 margin-block-start: var( --ui-shell-page-header-content-margin-block-start )',
    'resources/css/components/ui-shell/content.css:142 margin: 0',
    'resources/css/components/ui-shell/content.css:23 margin-block-start: var(--ui-shell-header-block-size)',
    'resources/css/components/ui-shell/content.css:27 margin-inline-start: var(--ui-shell-side-nav-collapsed-inline-size)',
    'resources/css/components/ui-shell/content.css:32 margin-inline-start: var(--ui-shell-side-nav-expanded-inline-size)',
    'resources/css/components/ui-shell/content.css:58 margin-block-end: var( --ui-shell-page-header-breadcrumb-margin-block-end )',
    'resources/css/components/ui-shell/content.css:68 margin: 0',
    'resources/css/components/ui-shell/content.css:82 margin-inline: var(--ui-shell-page-header-breadcrumb-gap)',
    'resources/css/components/ui-shell/header-actions.css:140 margin: 0',
    'resources/css/components/ui-shell/header-actions.css:236 margin: 0',
    'resources/css/components/ui-shell/header-actions.css:278 margin: 0',
    'resources/css/components/ui-shell/header-actions.css:403 margin-inline-start: auto',
    'resources/css/components/ui-shell/header-actions.css:435 margin: 0',
    'resources/css/components/ui-shell/header-actions.css:446 margin-block-start: var(--ui-spacing-01)',
    'resources/css/components/ui-shell/header-actions.css:463 margin-block-end: var(--ui-spacing-03)',
    'resources/css/components/ui-shell/header-actions.css:524 margin: 0',
    'resources/css/components/ui-shell/header-actions.css:591 margin: 0',
    'resources/css/components/ui-shell/header-actions.css:638 margin: 0',
    'resources/css/components/ui-shell/header-actions.css:671 margin: var(--ui-spacing-05) var(--ui-spacing-05) 0',
    'resources/css/components/ui-shell/header-actions.css:746 margin: 0',
    'resources/css/components/ui-shell/header-actions.css:801 margin-block-start: var( --ui-shell-notification-status-margin-block-start )',
    'resources/css/components/ui-shell/header-actions.css:827 margin-block-end: var(--ui-spacing-02)',
    'resources/css/components/ui-shell/header-actions.css:845 margin-block-start: var(--ui-spacing-01)',
    'resources/css/components/ui-shell/header-actions.css:859 margin-block-start: var(--ui-spacing-02)',
    'resources/css/components/ui-shell/header.css:228 margin: 0',
    'resources/css/components/ui-shell/header.css:368 margin: 0',
    'resources/css/components/ui-shell/header.css:424 margin-inline-start: var( --ui-shell-header-menu-arrow-margin-inline-start )',
    'resources/css/components/ui-shell/header.css:43 margin: 0',
    'resources/css/components/ui-shell/header.css:453 margin: -1px',
    'resources/css/components/ui-shell/header.css:72 margin-block-start: 0',
    'resources/css/components/ui-shell/side-nav.css:122 margin: 0',
    'resources/css/components/ui-shell/side-nav.css:148 margin: 0',
    'resources/css/components/ui-shell/side-nav.css:201 margin: var(--ui-spacing-03) var(--ui-shell-header-menu-item-padding-inline)',
    'resources/css/components/ui-shell/side-nav.css:224 margin: 0',
    'resources/css/components/ui-shell/side-nav.css:276 margin: 0',
    'resources/css/components/ui-shell/side-nav.css:331 margin: 0',
    'resources/css/components/ui-shell/side-nav.css:458 margin-inline-end: var(--ui-shell-side-nav-icon-gap)',
    'resources/css/components/ui-shell/side-nav.css:512 margin: 0',
    'resources/css/components/ui-shell/side-nav.css:522 margin-block-end: var(--ui-spacing-07)',
    'resources/css/components/ui-shell/side-nav.css:621 margin: 0',
    'resources/css/components/ui-shell/side-nav.css:630 margin: 0',
    'resources/css/components/ui-shell/side-nav.css:639 margin: 0',
    'resources/css/components/ui-shell/side-nav.css:692 margin: 0',
    'resources/css/components/ui-shell/side-nav.css:700 margin: 0',
    'resources/css/components/ui-shell/side-nav.css:711 margin: 0',
    'resources/css/components/ui-shell/side-nav.css:722 margin: 0',
    'resources/css/components/ui-shell/switcher.css:24 margin: 0',
    'resources/css/components/ui-shell/switcher.css:36 margin-block-start: 1rem',
    'resources/css/components/ui-shell/switcher.css:42 margin: 0.5rem 1rem',
];
