<?php

declare(strict_types=1);

return [
    'resources/css/components/accordion.css:232 @media (width >= 30rem)',
    'resources/css/components/accordion.css:239 @media (width >= 40rem)',
    'resources/css/components/actionable-notification.css:282 @media (min-width: 42rem)',
    'resources/css/components/actionable-notification.css:391 @media (min-width: 42rem)',
    'resources/css/components/actionable-notification.css:41 @media (min-width: 42rem)',
    'resources/css/components/actionable-notification.css:48 @media (min-width: 66rem)',
    'resources/css/components/actionable-notification.css:54 @media (min-width: 99rem)',
    'resources/css/components/actionable-notification.css:648 @media (min-width: 42rem)',
    'resources/css/components/breadcrumb.css:30 @media (min-width: 42rem)',
    'resources/css/components/data-table.css:78 @media (min-width: 42rem)',
    'resources/css/components/data-table.css:85 @media (min-width: 66rem)',
    'resources/css/components/dialog.css:207 @media (width >= 42rem)',
    'resources/css/components/dialog.css:213 @media (width >= 66rem)',
    'resources/css/components/dialog.css:64 @media (width >= 42rem)',
    'resources/css/components/dialog.css:70 @media (width >= 66rem)',
    'resources/css/components/dialog.css:76 @media (width >= 82rem)',
    'resources/css/components/file-uploader.css:252 @media (max-width: 410px)',
    'resources/css/components/inline-notification.css:235 @media (min-width: 42rem)',
    'resources/css/components/inline-notification.css:284 @media (min-width: 42rem)',
    'resources/css/components/inline-notification.css:404 @media (min-width: 42rem)',
    'resources/css/components/inline-notification.css:41 @media (min-width: 42rem)',
    'resources/css/components/inline-notification.css:48 @media (min-width: 66rem)',
    'resources/css/components/inline-notification.css:54 @media (min-width: 99rem)',
    'resources/css/components/modal.css:173 @media (width >= 42rem)',
    'resources/css/components/modal.css:181 @media (width >= 66rem)',
    'resources/css/components/modal.css:188 @media (width >= 82rem)',
    'resources/css/components/modal.css:297 @media (width >= 42rem)',
    'resources/css/components/modal.css:304 @media (width >= 66rem)',
    'resources/css/components/modal.css:312 @media (width >= 82rem)',
    'resources/css/components/modal.css:335 @media (width >= 42rem)',
    'resources/css/components/modal.css:342 @media (width >= 66rem)',
    'resources/css/components/modal.css:359 @media (width >= 82rem)',
    'resources/css/components/modal.css:370 @media (width >= 42rem)',
    'resources/css/components/modal.css:377 @media (width >= 66rem)',
    'resources/css/components/modal.css:385 @media (width >= 82rem)',
    'resources/css/components/page-header.css:263 @media (width <= 42rem)',
    'resources/css/components/tabs.css:1009 @media (min-width: 66rem)',
    'resources/css/components/tabs.css:800 @media (min-width: 66rem)',
    'resources/css/components/toast-notification.css:38 @media (min-width: 99rem)',
    'resources/css/components/ui-shell/header-actions.css:528 @media (max-width: 79.98rem)',
    'resources/css/components/ui-shell/header.css:141 @media (min-width: 66rem)',
    'resources/css/components/ui-shell/header.css:169 @media (max-width: 41.98rem)',
    'resources/css/components/ui-shell/header.css:206 @media (min-width: 66rem)',
    'resources/css/components/ui-shell/header.css:61 @media (max-width: 41.98rem)',
    'resources/css/components/ui-shell/side-nav.css:39 @media (max-width: 65.98rem)',
    'resources/css/components/ui-shell/side-nav.css:503 @media (max-width: 65.98rem)',
    'resources/css/components/ui-shell/side-nav.css:518 @media (max-width: 65.98rem)',
    'resources/css/components/ui-shell/side-nav.css:74 @media (max-width: 65.98rem)',
];
