<?php

declare(strict_types=1);

return [
    'resources/css/components/badge-indicator.css:37 font-size: 0.75rem',
    'resources/css/components/badge-indicator.css:38 font-weight: 400',
    'resources/css/components/badge-indicator.css:39 line-height: 1rem',
    'resources/css/components/code-snippet.css:114 font-family: var(--ui-font-family-mono, monospace)',
    'resources/css/components/code-snippet.css:43 font-family: var(--ui-font-family-mono, monospace)',
    'resources/css/components/code-snippet.css:54 font-family: var(--ui-font-family-mono, monospace)',
    'resources/css/components/content-switcher.css:96 font-weight: 400',
    'resources/css/components/data-table-sort.css:50 line-height: 1',
    'resources/css/components/data-table-sort.css:85 line-height: 1',
    'resources/css/components/dropdown.css:428 line-height: 1rem',
    'resources/css/components/form.css:268 font-weight: 400',
    'resources/css/components/form.css:313 font-weight: 400',
    'resources/css/components/form.css:73 font-weight: var(--ui-input-label-weight, 400)',
    'resources/css/components/form.css:74 line-height: 1rem',
    'resources/css/components/list-box.css:764 font-weight: 400',
    'resources/css/components/list-box.css:765 line-height: 1rem',
    'resources/css/components/loading.css:114 font-size: 0.875rem',
    'resources/css/components/loading.css:115 line-height: 1.25rem',
    'resources/css/components/loading.css:27 font-size: 0.875rem',
    'resources/css/components/loading.css:28 line-height: 1.25rem',
    'resources/css/components/loading.css:50 font-size: 0.875rem',
    'resources/css/components/modal.css:207 font-weight: 400',
    'resources/css/components/number-input.css:77 font-weight: 400',
    'resources/css/components/overflow-menu.css:390 font-weight: 400',
    'resources/css/components/pagination-nav.css:97 line-height: 1',
    'resources/css/components/progress-indicator.css:117 line-height: 1.45',
    'resources/css/components/slug.css:103 font-size: 0.5625rem',
    'resources/css/components/slug.css:104 line-height: 0.75rem',
    'resources/css/components/slug.css:113 font-size: 0.75rem',
    'resources/css/components/slug.css:114 line-height: 1rem',
    'resources/css/components/slug.css:123 font-size: 0.75rem',
    'resources/css/components/slug.css:124 line-height: 1rem',
    'resources/css/components/slug.css:133 font-size: 1rem',
    'resources/css/components/slug.css:134 line-height: 1.3125rem',
    'resources/css/components/slug.css:143 font-size: 1rem',
    'resources/css/components/slug.css:144 line-height: 1.3125rem',
    'resources/css/components/slug.css:153 font-size: 1rem',
    'resources/css/components/slug.css:154 line-height: 1.3125rem',
    'resources/css/components/slug.css:163 font-size: 1.25rem',
    'resources/css/components/slug.css:164 line-height: 1.625rem',
    'resources/css/components/slug.css:208 font-size: 0.875rem',
    'resources/css/components/slug.css:346 font-size: 0.75rem',
    'resources/css/components/slug.css:357 font-size: 1rem',
    'resources/css/components/slug.css:390 font-size: 0.875rem',
    'resources/css/components/status.css:20 font-size: 0.75rem',
    'resources/css/components/status.css:21 font-weight: 600',
    'resources/css/components/status.css:22 letter-spacing: 0.15em',
    'resources/css/components/status.css:23 line-height: 1rem',
    'resources/css/components/status.css:96 font-size: 0.75rem',
    'resources/css/components/status.css:97 font-weight: 500',
    'resources/css/components/status.css:98 line-height: 1rem',
    'resources/css/components/tabs.css:453 line-height: calc(3rem - (var(--ui-spacing-03) * 2))',
    'resources/css/components/tabs.css:724 line-height: calc(3rem - (var(--ui-spacing-03) * 2))',
    'resources/css/components/tree-view.css:200 line-height: 1.2',
    'resources/css/components/ui-shell/content.css:104 font-size: var(--ui-type-heading-05-font-size, 2rem)',
    'resources/css/components/ui-shell/content.css:105 font-weight: 400',
    'resources/css/components/ui-shell/content.css:106 line-height: var(--ui-type-heading-05-line-height, 2.5rem)',
    'resources/css/components/ui-shell/content.css:114 font-size: var(--ui-type-body-01-font-size, 0.875rem)',
    'resources/css/components/ui-shell/content.css:115 line-height: var(--ui-type-body-01-line-height, 1.25rem)',
    'resources/css/components/ui-shell/content.css:161 font-weight: 400',
    'resources/css/components/ui-shell/content.css:77 font-size: var(--ui-type-label-01-font-size, 0.75rem)',
    'resources/css/components/ui-shell/content.css:78 line-height: var(--ui-type-label-01-line-height, 1rem)',
    'resources/css/components/ui-shell/header-actions.css:366 line-height: 1',
    'resources/css/components/ui-shell/header-actions.css:59 line-height: 1',
    'resources/css/components/ui-shell/header-actions.css:640 font-size: var(--ui-type-heading-compact-01-font-size, 1rem)',
    'resources/css/components/ui-shell/header-actions.css:642 line-height: var(--ui-type-heading-compact-01-line-height, 1.375rem)',
    'resources/css/components/ui-shell/header-actions.css:698 line-height: 1',
    'resources/css/components/ui-shell/side-nav.css:130 letter-spacing: 0.16px',
    'resources/css/components/ui-shell/side-nav.css:232 font-size: 0.875rem',
    'resources/css/components/ui-shell/side-nav.css:234 letter-spacing: 0.16px',
    'resources/css/components/ui-shell/side-nav.css:235 line-height: 1.125rem',
    'resources/css/components/ui-shell/side-nav.css:390 font-size: 0.875rem',
    'resources/css/components/ui-shell/side-nav.css:392 letter-spacing: 0.16px',
    'resources/css/components/ui-shell/side-nav.css:393 line-height: 1.125rem',
    'resources/css/components/ui-shell/side-nav.css:412 font-size: 0.875rem',
    'resources/css/components/ui-shell/side-nav.css:413 letter-spacing: 0.1px',
    'resources/css/components/ui-shell/side-nav.css:414 line-height: 1.25rem',
    'resources/css/components/ui-shell/switcher.css:53 font-size: 0.875rem',
    'resources/css/components/ui-shell/switcher.css:54 font-weight: 600',
    'resources/css/components/ui-shell/switcher.css:55 letter-spacing: 0.16px',
    'resources/css/components/ui-shell/switcher.css:56 line-height: 1.125rem',
];
